### ISSUE TITLE
Fix font-family on doc page

### ISSUE THREAD

**Issue by GreenRobot777** [terminusdb/terminusdb-doc#20]
**Describe the bug**
Ugly font-family for text and code

**To Reproduce**
Steps to reproduce the behavior. e.g. I resize the window to a small dimension

**Expected behavior**
```css
body {
  font-family: Arial, Helvetica, sans-serif;
}

code {
  font-family: 'Courier New', Courier, monospace;
}
```

**Screenshots**
AS-IS
![image](https://user-images.githubusercontent.com/14993551/111082532-62acf980-853b-11eb-8bbe-6c04c0554b5c.png)

TO-BE
![image](https://user-images.githubusercontent.com/14993551/111082504-4446fe00-853b-11eb-9fdf-7f2ea11ec1ab.png)
